Use ContextClassLoader for FastStringService.
Without this line, we get an error when the plugin is run from Icy.

java.lang.RuntimeException: Cellpose failed: Unable to load FastStringService
at plugins.tinevez.appose.cellpose.Cellpose3.execute(Cellpose3.java:256)
at plugins.adufour.ezplug.EzPlug.lambda$new$0(EzPlug.java:103)
at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.RuntimeException: Unable to load FastStringService
at org.apache.groovy.json.internal.FastStringUtils.getService(FastStringUtils.java:56)
at org.apache.groovy.json.internal.FastStringUtils.toCharArray(FastStringUtils.java:66)
at org.apache.groovy.json.internal.CharBuf.addJsonFieldName(CharBuf.java:524)
at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:400)
at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:389)
at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:204)
at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:168)
at groovy.json.DefaultJsonGenerator.toJson(DefaultJsonGenerator.java:102)
at org.apposed.appose.util.Messages.encode(Messages.java:75)